# Generated by Django 5.1.4 on 2025-01-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cart_address_cart_card_text_cart_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cart',
            name='card_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cart',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
