# Generated by Django 5.1.4 on 2025-01-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
