# Generated by Django 5.1.4 on 2025-01-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_address_order_card_text_order_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
