# Generated by Django 5.1.4 on 2025-01-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='card_text',
        ),
        migrations.AddField(
            model_name='cart',
            name='card_text_choice',
            field=models.CharField(choices=[('custom', 'Свой текст'), ('ready', 'Готовый текст')], default='custom', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='custom_card_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='no_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='no_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='ready_card_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
