# Generated by Django 5.1.4 on 2025-01-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_cart_card_text_cart_card_text_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='custom_card_text',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ready_card_text',
        ),
        migrations.AddField(
            model_name='cart',
            name='card_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cart',
            name='card_text_choice',
            field=models.CharField(blank=True, choices=[('С днем рождения!', 'С днем рождения!'), ('С годовщиной!', 'С годовщиной!'), ('С любовью!', 'С любовью!')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
