# Generated by Django 5.1.4 on 2025-01-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_cart_custom_card_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='card_text_choice',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='no_card',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='no_signature',
        ),
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cart',
            name='card_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cart',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
